# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Scrape and Upload

on:
  schedule:
    - cron: '*/30 12-23 * * *'
    - cron: '*/30 0-5 * * *'

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run the Python script
      env:
        GITHUB_APP_ID: ${{ secrets.GITHUB_APP_ID }}
        GITHUB_INSTALLATION_ID: ${{ secrets.GITHUB_INSTALLATION_ID }}
        GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
      run: python cron/scrape_and_upload.py
